### ISSUE TITLE
Minimal template not possible to choose

### ISSUE THREAD

**Issue by fussinatto** [Veams/veams#8]
Hello Mr.Fitzner :),
by generating a new project, arrow keys on first question do not work (minimal installation cannot be selected). I hope its easily fixed ;)

```
generator-veams: 7.3.0
veams-cli: 1.3.1
insertor: 1.0.4
```

Cheers mate.

P.S. I guess this issue belongs to generator-veams, sorry.

**Comment by Sebastian-Fitzner** [comment]
It is a windows machine? Then this is a node issue... will search for the reference.

I guess it should be fixed in the newest node version, but check it for sure. 

How is it going? Let's chat in the next time 😉.

**Comment by Sebastian-Fitzner** [comment]
https://github.com/SBoudrias/Inquirer.js/issues/266
